#!/usr/bin/env bash
# ==============================================================================
# Financial Research Studio - Cross-Account GCP Automated Deployment Script
# ==============================================================================
set -e

echo "============================================================"
echo " Financial Research Studio - GCP Deployment Script"
echo "============================================================"

# 1. Verify CLI Tool Prerequisites
for tool in gcloud python3 agents-cli gsutil; do
    if ! command -v $tool &> /dev/null; then
        echo "Error: Required CLI tool '$tool' is not installed or not in PATH."
        echo "Please install $tool and ensure you are logged in via 'gcloud auth login'."
        exit 1
    fi
done

# 2. Configure Target GCP Project ID & Region
PROJECT_ID=$(gcloud config get-value project 2>/dev/null || true)
if [ -z "$PROJECT_ID" ] || [ "$PROJECT_ID" = "(unset)" ]; then
    read -p "Enter target GCP Project ID: " PROJECT_ID
    gcloud config set project "$PROJECT_ID"
fi

read -p "Enter GCP Region (default: us-east1): " LOCATION
LOCATION=${LOCATION:-us-east1}

echo "--> Target GCP Project ID: $PROJECT_ID"
echo "--> Target GCP Region:     $LOCATION"

# 3. Retrieve Project Number
PROJECT_NUMBER=$(gcloud projects describe "$PROJECT_ID" --format="value(projectNumber)")
echo "--> GCP Project Number:   $PROJECT_NUMBER"

# 4. Enable Required GCP APIs
echo "--> Enabling required Google Cloud Service APIs..."
gcloud services enable \
    aiplatform.googleapis.com \
    run.googleapis.com \
    firestore.googleapis.com \
    storage.googleapis.com \
    cloudbuild.googleapis.com \
    iam.googleapis.com \
    --project="$PROJECT_ID"

# 5. Create & Configure Public Cloud Storage Bucket for Assets
BUCKET_NAME="${PROJECT_ID}-financial-studio-assets"
echo "--> Setting up Cloud Storage bucket: gs://${BUCKET_NAME}..."
if ! gsutil ls -b "gs://${BUCKET_NAME}" &>/dev/null; then
    gsutil mb -p "$PROJECT_ID" -l "$LOCATION" -b on "gs://${BUCKET_NAME}"
    gsutil iam ch allUsers:objectViewer "gs://${BUCKET_NAME}"
    echo "--> Created bucket gs://${BUCKET_NAME} with public read permissions."
else
    echo "--> Bucket gs://${BUCKET_NAME} already exists."
fi

# 6. Initialize Firestore Database in Native Mode (if not present)
echo "--> Ensuring Firestore Database is initialized..."
if ! gcloud firestore databases describe --project="$PROJECT_ID" &>/dev/null; then
    echo "--> Creating default Firestore database in Native mode..."
    gcloud firestore databases create --location="$LOCATION" --project="$PROJECT_ID" || true
fi

# 7. Update Hardcoded Project ID & Bucket Name in app/agent.py
echo "--> Updating PROJECT_ID and BUCKET_NAME in app/agent.py..."
python3 -c "
import re
path = 'app/agent.py'
content = open(path).read()
content = re.sub(r'PROJECT_ID = \".*?\"', f'PROJECT_ID = \"${PROJECT_ID}\"', content)
content = re.sub(r'BUCKET_NAME = \".*?\"', f'BUCKET_NAME = \"${BUCKET_NAME}\"', content)
open(path, 'w').write(content)
"

# 8. Deploy Agent to Agent Runtime via agents-cli
echo "--> Deploying agent runtime via agents-cli..."
agents-cli deploy --project="$PROJECT_ID" --location="$LOCATION"

# 9. Extract Deployed Reasoning Engine Resource Name
echo "--> Reading deployment_metadata.json..."
if [ ! -f "deployment_metadata.json" ]; then
    echo "Error: deployment_metadata.json was not generated by agents-cli deploy."
    exit 1
fi

RESOURCE_NAME=$(python3 -c "import json; print(json.load(open('deployment_metadata.json')).get('remote_agent_runtime_id', ''))")
if [ -z "$RESOURCE_NAME" ]; then
    echo "Error: Could not retrieve remote_agent_runtime_id from deployment_metadata.json."
    exit 1
fi
echo "--> Deployed Reasoning Engine Resource Name: $RESOURCE_NAME"

# 10. Grant Necessary IAM Permissions to Agent Engine Service Account
AGENT_SA="service-${PROJECT_NUMBER}@gcp-sa-aiplatform-re.iam.gserviceaccount.com"
echo "--> Granting Firestore & Storage permissions to Agent Service Account ($AGENT_SA)..."
gcloud projects add-iam-policy-binding "$PROJECT_ID" \
    --member="serviceAccount:${AGENT_SA}" \
    --role="roles/datastore.user" --quiet || true

gsutil iam ch "serviceAccount:${AGENT_SA}:roles/storage.objectAdmin" "gs://${BUCKET_NAME}" || true

# 11. Deploy FastAPI Proxy & Chat UI to Cloud Run
echo "--> Deploying Frontend Proxy Service to Cloud Run..."
gcloud run deploy financial-research-studio-frontend \
    --source ./frontend \
    --region "$LOCATION" \
    --project "$PROJECT_ID" \
    --allow-unauthenticated \
    --set-env-vars AGENT_ENGINE_RESOURCE_NAME="$RESOURCE_NAME",AGENT_DIRECTORY="app"

# 12. Grant Cloud Run Compute Service Account AI Platform Access
COMPUTE_SA="${PROJECT_NUMBER}-compute@developer.gserviceaccount.com"
echo "--> Granting roles/aiplatform.user to Cloud Run Service Account ($COMPUTE_SA)..."
gcloud projects add-iam-policy-binding "$PROJECT_ID" \
    --member="serviceAccount:${COMPUTE_SA}" \
    --role="roles/aiplatform.user" --quiet

# 13. Output Deployment Summary
FRONTEND_URL=$(gcloud run services describe financial-research-studio-frontend --region "$LOCATION" --project "$PROJECT_ID" --format="value(status.url)")

echo "============================================================"
echo " Deployment Successfully Completed!"
echo "============================================================"
echo " Frontend Service URL : $FRONTEND_URL"
echo " Agent Resource Name  : $RESOURCE_NAME"
echo " Public Asset Bucket  : gs://$BUCKET_NAME"
echo "============================================================"
